# Generated by Django 5.1.1 on 2026-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_owner_cat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
