# Generated by Django 5.1.1 on 2026-04-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_achivement_achievementcat_cat_achievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achivement',
            new_name='Achievement',
        ),
    ]
